### ISSUE TITLE
error on find command on mac

### ISSUE THREAD

**Issue by zenfish** [philwhiles/frettler#17]
First - really interesting project, thanks for putting it out! It built fine, seems to work for the various simple cases so far... but found a minor error that showed up in the demo script, but also when trying to run the find subcommand manually.  

This is on a mac (10.15.7), using (output of `exec java - -version`, just like your shell script uses):

`
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9)
OpenJDK 64-Bit Server VM (build 15.0.1+9, mixed mode, sharing)
`

Now I realize you say Java 11 in your README, but that version no longer unsupported on the mac... so you could ignore this, but also perhaps it's a minor fix (I last programmed in java like 20 years ago :)). If nothing else I could bundle it up in docker or whatnot and use J11 if I really needed this feature.

Anyway, all else works seemingly great, but here's the error I was seeing, starting when running the `./demo` program, and then....
`
14) Standard guitar, lookup chord and display vertically

> ./frettler guitar find -n c,e,g 
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "this.position" is null
	at me.flotsam.frettler.command.FrettedInstrumentCommand.handleFindCommand(FrettedInstrumentCommand.java:265)
	at me.flotsam.frettler.command.FrettedInstrumentCommand.exec(FrettedInstrumentCommand.java:131)
	at me.flotsam.frettler.command.GuitarCommand.run(GuitarCommand.java:33)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at me.flotsam.frettler.Main.main(Main.java:46)
==============================================================================================================================
`

Trying some manual examples from the dox -

`
./frettler guitar find --notes ./frettler guitar find --digits x,0,2,2,1,0
Invalid value for option '--notes' (<notes>): expected one of [C, D, E, F, G, A, B, Cs, Ds, Es, Fs, Gs, As, Bs, Cb, Db, Eb, Fb, Gb, Ab, Bb] (case-insensitive) but was './frettler'
`

Also `./frettler guitar find -n c,e,g`, (and `-n c,e` and `-n c`) die with:
`
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "this.position" is null
`

**Comment by philwhiles** [comment]
Thanks for bug report. Glad you are using frettler - hope you find it useful. 
Happy to hear of bugs and any suggestions for improvements.
Fixed that one now btw - pull and rebuild and let me know if you have any more problems.

**Comment by philwhiles** [comment]
Pull again Dan and let me know how you get on

**Comment by zenfish** [comment]
Works like a champ, thanks!  And the build script is great, wish more people had something like that ;)  (The two commands mashed together was something git did, not sure why, but they both work now as well.)
