### ISSUE TITLE
Feature request: A docker build and release on dockerhub would be useful

### ISSUE THREAD

**Issue by travis-bear** [philwhiles/frettler#5]
Not everyone wants to install Java.  It would be nice to have a docker build, and a release on docker hub

**Comment by philwhiles** [comment]
And have them install Docker instead?

**Comment by travis-bear** [comment]
Look, this is your project, do what you want.  I'm just saying I think it would be helpful.

**Comment by argais** [comment]
@philwhiles Would you take a PR to add this?

**Comment by philwhiles** [comment]
I would consider it of course, as an alternative way to running frettler. I use Docker in my day job, everything gets built as Docker images and deployed into Google Cloud. It's just that I know installing Docker is not a lightweight thing to do, particularly if you keep it running in the background. But go for it.

A docker build would be useful,  btw.

**Comment by philwhiles** [comment]
Obviously not then.
